// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Timesheet.Api.Models
{
    public partial class ApprovalHistory
    {
        public int Id { get; set; }
        public DateTime? ActionDate { get; set; }
        public int? ActionType { get; set; }
        public int? IdUser { get; set; }
        public int? IdTimesheetControl { get; set; }
        public int? TimesheetType { get; set; }
        public string Comments { get; set; }

        public virtual User IdUserNavigation { get; set; }
    }
}