// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Timesheet.Api.Models
{
    public partial class Client
    {
        public Client()
        {
            Project = new HashSet<Project>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Comments { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string StateProvince { get; set; }
        public string ZipPostalCode { get; set; }
        public string Country { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public bool? Disabled { get; set; }
        public decimal? DefaultBillingRateAmount { get; set; }
        public string DefaultBillingRateDescription { get; set; }
        public string BillingGlaccount { get; set; }
        public string BillingCurrencyCode { get; set; }
        public decimal? GstratePercent { get; set; }
        public string ApvendorId { get; set; }
        public string ApcurrencyCode { get; set; }
        public string OriginalCode { get; set; }
        public string Group { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedIp { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedIp { get; set; }
        public string CreatedMacAddress { get; set; }
        public string UpdatedMacAddress { get; set; }

        public virtual ICollection<Project> Project { get; set; }
    }
}