// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Timesheet.Api.Models
{
    public partial class CostCenter
    {
        public int Costcenterid { get; set; }
        public string Costcentername { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedIp { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedIp { get; set; }
        public bool? Disabled { get; set; }
        public string CreatedMacAddress { get; set; }
        public string UpdatedMacAddress { get; set; }
    }
}