// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Timesheet.Api.Models
{
    public partial class General
    {
        public int GralId { get; set; }
        public string Value { get; set; }
        public bool? DefaultValue { get; set; }
        public string GralGroup { get; set; }
        public string Type { get; set; }
    }
}