// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Timesheet.Api.Models
{
    public partial class ProjectHasUser
    {
        public int Puid { get; set; }
        public int? ProjectId { get; set; }
        public int? UserId { get; set; }

        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}