// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Timesheet.Api.Models
{
    public partial class Project
    {
        public Project()
        {
            ProjectHasUser = new HashSet<ProjectHasUser>();
        }

        /// <summary>
        /// Project ID
        /// </summary>
        public int Id { get; set; }
        public string Name { get; set; }
        public string ProjectCode { get; set; }
        public string Description { get; set; }
        public bool? TimeEntryAllowed { get; set; }
        public DateTime? EntryStartDate { get; set; }
        public DateTime? EntryEndDate { get; set; }
        public bool? ClosedStatus { get; set; }
        public string UdfGroups { get; set; }
        public string UdfPlpCostCenter { get; set; }
        public string UdfProjectType { get; set; }
        public string UdfAudience { get; set; }
        public int? ProjectLeaderId { get; set; }
        public int? ClientId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedIp { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedIp { get; set; }
        public string CreatedMacAddress { get; set; }
        public string UpdatedMacAddress { get; set; }
        public string TimeExpenseEntryType { get; set; }

        public virtual Client Client { get; set; }
        public virtual ICollection<ProjectHasUser> ProjectHasUser { get; set; }
    }
}