// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Timesheet.Api.Models
{
    public partial class TimesheetControl
    {
        public int TimesheetPeriodId { get; set; }
        public DateTime TimesheetPeriod { get; set; }
        public int UserId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int ApprovalStatusId { get; set; }
        public int? UserTemplateId { get; set; }

        public virtual ApprovalStatus ApprovalStatus { get; set; }
        public virtual User User { get; set; }
    }
}