// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Timesheet.Api.Models
{
    public partial class TimesheetType
    {
        public int TimeTemplateId { get; set; }
        public string TemplateName { get; set; }
        public string TimeTemplateDesc { get; set; }
    }
}