// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Timesheet.Api.Models
{
    public partial class TimeOff
    {
        public TimeOff()
        {
            Approvals = new HashSet<Approvals>();
        }

        public int TimeOffId { get; set; }
        public string TimeOffName { get; set; }
        public string TimeOffCode { get; set; }
        public bool? Disabled { get; set; }

        public virtual ICollection<Approvals> Approvals { get; set; }
    }
}