// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Timesheet.Api.Models
{
    public partial class TimesheetData
    {
        public long TimesheetId { get; set; }
        public DateTime Timesheetperiod { get; set; }
        public DateTime Startdate { get; set; }
        public DateTime Enddate { get; set; }
        public DateTime Entrydate { get; set; }
        public int Userid { get; set; }
        public int? DepartmentId { get; set; }
        public int? Supervisorid { get; set; }
        public int? Projectid { get; set; }
        public string Projectcode { get; set; }
        public string Projectname { get; set; }
        public string Projectdescription { get; set; }
        public string Billingmethod { get; set; }
        public int? Clientid { get; set; }
        public decimal? BillingpercentageRatio { get; set; }
        public int? Projectleaderid { get; set; }
        public int? Clientuserid { get; set; }
        public int? Tasktimeoffid { get; set; }
        public string Tasktimeoffname { get; set; }
        public string Htasktimeoffname { get; set; }
        public string Tasktimeoffcode { get; set; }
        public int? ActivityId { get; set; }
        public string ActivityName { get; set; }
        public string ActivityCode { get; set; }
        public int? Billable { get; set; }
        public string Billablename { get; set; }
        public decimal? NonBillableHours { get; set; }
        public decimal? BillableHours { get; set; }
        public decimal? TimeOffHours { get; set; }
        public decimal? ProjectHours { get; set; }
        public decimal? TotalHours { get; set; }
        public string Comments { get; set; }
        public int? Rowposition { get; set; }
        public int? Approvalstatus { get; set; }
        public string Taskinfo1 { get; set; }
        public string Taskinfo2 { get; set; }
        public string Taskinfo3 { get; set; }
        public string Taskinfo4 { get; set; }
        public string Taskinfo5 { get; set; }
        public string Taskinfo6 { get; set; }
        public string Taskinfo7 { get; set; }
        public string Taskinfo8 { get; set; }
        public string Taskinfo9 { get; set; }
        public string Taskinfo10 { get; set; }
        public string Rpinfo1 { get; set; }
        public string Rpinfo2 { get; set; }
        public string Rpinfo3 { get; set; }
        public string Rpinfo4 { get; set; }
        public string Rpinfo5 { get; set; }
        public string Ttinfo1 { get; set; }
        public string Ttinfo2 { get; set; }
        public string Ttinfo3 { get; set; }
        public string Ttinfo4 { get; set; }
        public string Ttinfo5 { get; set; }
        public string Teinfo1 { get; set; }
        public string Teinfo2 { get; set; }
        public string Teinfo3 { get; set; }
        public string Teinfo4 { get; set; }
        public string Teinfo5 { get; set; }
        public int? Reportperiodid { get; set; }
        public int? Tasktimesheetid { get; set; }
        public int? Timesheetentryid { get; set; }
        public string Taskname1 { get; set; }
        public string Fulltaskname { get; set; }
        public string Cellcomments { get; set; }
        public decimal? Billingpercentage { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Employeeid { get; set; }
        public string Userinfo1 { get; set; }
        public string Userinfo2 { get; set; }
        public string Userinfo3 { get; set; }
        public string Userinfo4 { get; set; }
        public string Userinfo5 { get; set; }
        public string Loginname { get; set; }
        public string Employeetypeid { get; set; }
        public string Employeetypename { get; set; }
        public string PlName { get; set; }
        public string PlEmail { get; set; }
        public string CuName { get; set; }
        public string CuEmail { get; set; }
        public string Supervisorname { get; set; }
        public int? DepId { get; set; }
        public string Departmentname { get; set; }
        public string Departmentcode { get; set; }
        public string Clientname { get; set; }
        public string Clientcode { get; set; }
        public int? UserGroupSetId { get; set; }
        public string UserGroupSetName { get; set; }
        public int? UserGroupId { get; set; }
        public string UserGroupName { get; set; }
    }
}