// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Timesheet.Api.Models
{
    public partial class TranslationMappingsActivityGrouping
    {
        public int Id { get; set; }
        public string InitialValue { get; set; }
        public string TransformedValue { get; set; }
    }
}