// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Timesheet.Api.Models
{
    public partial class UserSelectAct
    {
        public int UserId { get; set; }
        public string Activities { get; set; }
    }
}