// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Timesheet.Api.Models
{
    public partial class UserActivityCode
    {
        public int UserActivityCodeId { get; set; }
        public int? ActivityId { get; set; }
        public bool? IsActivityEnabled { get; set; }
        public string ActivityName { get; set; }
        public string ActivityCode { get; set; }
        public int? UserId { get; set; }
        public bool? IsSampleUser { get; set; }
        public bool? IsUserDisabled { get; set; }
        public string UserTitle { get; set; }
        public string PositionTitle { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DepartmentName { get; set; }
        public bool? IsPrimaryDepartment { get; set; }
        public string CostCenterGroup { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedIp { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedIp { get; set; }
        public bool? Disabled { get; set; }
        public string CreatedMacAddress { get; set; }
        public string UpdatedMacAddress { get; set; }
    }
}