// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Timesheet.Api.Models
{
    public partial class User
    {
        public User()
        {
            Approvals = new HashSet<Approvals>();
            InverseSubstituteUserNavigation = new HashSet<User>();
            ProjectHasUser = new HashSet<ProjectHasUser>();
        }

        public int Id { get; set; }
        public string ExternalId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string LoginName { get; set; }
        public bool? Disabled { get; set; }
        public bool? IsSampleUser { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? AccountExpiry { get; set; }
        public string Domain { get; set; }
        public string Email { get; set; }
        public string ExternalEmail { get; set; }
        public string OfflineEmail { get; set; }
        public TimeSpan? CurrentHoursPerDay { get; set; }
        public double? DefaultBillingRate { get; set; }
        public bool? DisablePasswordChange { get; set; }
        public bool? ForcePasswordChange { get; set; }
        public int? NumberOfTimesheetsPendingApproval { get; set; }
        public int? NumberOfTimesheetsWithPreviousApprovalAction { get; set; }
        public double? BillingRate { get; set; }
        public string JobTitle { get; set; }
        public string ReportsTo { get; set; }
        public double? ConvertDaysToHours { get; set; }
        public double? PlpmarkUp { get; set; }
        public string PositionTitle { get; set; }
        public int? RoleId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedIp { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedIp { get; set; }
        public string CreatedMacAddress { get; set; }
        public string UpdatedMacAddress { get; set; }
        public int? DepartmentId { get; set; }
        public int? EmpTypeId { get; set; }
        public int? SubstituteUser { get; set; }
        public int? SupervisorId { get; set; }
        public int? TimesheetTemplate { get; set; }

        public virtual Department Department { get; set; }
        public virtual EmployeeType EmpType { get; set; }
        public virtual User SubstituteUserNavigation { get; set; }
        public virtual ICollection<Approvals> Approvals { get; set; }
        public virtual ICollection<User> InverseSubstituteUserNavigation { get; set; }
        public virtual ICollection<ProjectHasUser> ProjectHasUser { get; set; }
    }
}